SFU.OMEの作成
extreal-dev/Extreal.Integration.SFU.OME pull request #1
Opened 2024-02-13 08:37 UTC by sus-yoshikane-t

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装

- [x] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [x] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [x] 静的解析で問題が見つからないことを確認しました
- [x] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました
- [ ] テストカバレッジが100%になることを確認しました
- [ ] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2024-02-19 12:29 UTC, sasuke9410 requested changes

2024-02-19 12:29 UTC, sasuke9410 commented on OMEServer~/README.md
> +  - OBS Studio
Extrealの使用用途だと、OBSを使った動画配信は使用しないと思うので、
READMEも合わせて修正した方がいいと思います。

2024-02-19 12:29 UTC, sasuke9410 commented on OMEServer~/ansible/README.md
> +## Ansible のインストール
ExtrealではAnsibleを使用していないと思うので、
項目を削除しておくべきだと思いました。
またansibleのディレクトリ自体も消すべきだと思いました。

2024-02-19 12:29 UTC, sasuke9410 commented on OMEServer~/efs/sample.env
STCから連携された状態だと、efsフォルダの中からsample.envやKeysディレクトリをリポジトリ直下におくようになっていますが、
Extrealだとefsを使用していないため、
・使用する.envとKeysディレクトリを最初からリポジトリ直下に配置する
・efsディレクトリを削除
してもいいのではないかと思いました。

2024-02-19 12:29 UTC, sasuke9410 commented on OMEServer~/docs/obs-live-settings.png
ExtrealではOBSを使った確認が不要なため、
画像を削除しておくべきだと思いました。
obs-output-settings.pngも同様です。

2024-02-19 12:29 UTC, sasuke9410 commented on package.json
> +    "com.endel.nativewebsocket": "1.1.4",
com.endelはOpenUPM経由でインストールしていると思うので、
Package Managerに"com.endel"を追加するという情報はどこかに必要だと思います。
このリポジトリのREADMEか、ガイドのどちらかに書く必要があると考えています。

2024-02-19 12:29 UTC, sasuke9410 commented on OMEServer~/docker-compose.yml
> +      #- ${SSL_SERVER_CERT}:${OME_TLS_CERT_PATH}:ro
今回プルリクを出しているブランチでは、
ローカル環境での動作を想定していると思います。
AWS上で動作する際には
・fullchain.pemとprivkeyのコメントアウト解除
・network_modeのコメントアウト
・OME_SERVER_URLの変更
が必要になると思いますが、これもREADMEかガイドのどちらかに書く必要があると考えています。

2024-02-19 12:29 UTC, sasuke9410 commented on OMEServer~/efs/sample.env
> +# 社内でWebSocketを繋ぐためには443ポートを使う（デフォルト: 3334）
フレームワークとしてリリースするものなので、
「社内では～」関連の記述は消した方がいいです。

2024-02-19 12:29 UTC, sasuke9410 commented on OMEServer~/keys
efsを削除することになる想定のため、
テキストファイルではなく、ディレクトリにした方がいいと思います。

2024-02-19 12:29 UTC, sasuke9410 commented on Samples~/MVS/ClientControl/ClientControlScope.cs
> +                        "stun:stun.l.google.com:19302",
Holidayの[P2PConfig](https://github.com/extreal-dev/Extreal.SampleApp.Holiday/blob/develop/Assets/Holiday/App/Config/P2PConfig.asset)だとSTUNサーバのURLは1つのみになっていますが、
複数指定されている理由はありますか？
他のライブラリに合わせているなら問題ないです。

2024-02-19 22:45 UTC, sasuke9410 commented on Runtime/Extreal.Integration.SFU.OME.asmdef
Checkタブで、check-analyzer-existenceがエラーになっています。
これはプルリク作成時に解消しておくべきものでしょうか？
それともレビュー後でよいのでしょうか？

2024-02-19 23:30 UTC, sasuke9410 commented on Runtime/OmeWebSocket.cs
> +            var currentRetryCount = subscribeRetryCounts.ContainsKey(message.ClientId) ? subscribeRetryCounts[message.ClientId] : 0;
以下に変更するのはどうでしょうか？
var currentRetryCount = subscribeRetryCounts.TryGetValue(message.ClientId, out var count) ? count : 0;

2024-02-19 23:31 UTC, sasuke9410 commented on Runtime/OmeConfig.cs
> +        /// <param name="url">URL of the signaling server</param>
urlではなく、serverUrlではないでしょうか？

2024-02-21 02:54 UTC, kiyohome requested changes

2024-02-21 02:54 UTC, kiyohome commented on OMEServer~/.env
> +# TLS/SSL証明書
ソースコメントは全部英語ではないでしょうか？

2024-02-21 02:54 UTC, kiyohome commented on OMEServer~/OMEServer.code-workspace
> +{
このファイルは必要ですか？

2024-02-21 02:54 UTC, kiyohome commented on OMEServer~/ansible/README.md
> +## Ansible のインストール
Extrealで必要なものだけにしてください。
もし含めて出すのであれば全てテスト、品質評価が必要になります。

2024-02-21 02:54 UTC, kiyohome commented on SignalingServer~/src/index.ts
> +const log = (message: string) => isLogging && console.log(message);
細かいですが、これだとログ出さない場合も文字列が生成されるので、関数を渡すようにした方がいいです。

2024-02-21 02:54 UTC, kiyohome commented on SignalingServer~/src/index.ts
> +  Deno.serve({
serveに渡すオプションのオブジェクトと、ログメッセージだけが違うだけではないですか？
後の処理は同じなら、そこだけ条件分岐した方がよくないでしょうか。

2024-02-21 02:54 UTC, kiyohome commented on SignalingServer~/src/index.ts
> +  let clientId = "";
こちら、いきなり代入したらダメなんでしょうか？
clientId = crypto.randomUUID();
そしたらconstにできそうに見えます。

2024-02-21 02:54 UTC, kiyohome commented on WebScripts~/src/OmeWebSocket.ts
> +                // const sdpMid = candidate.sdpMid;
コメントアウトは消しませんか？

2024-02-21 03:16 UTC, kiyohome requested changes

2024-02-21 03:16 UTC, kiyohome commented on SignalingServer~/docker-compose.yml
> +version: '3.8'
OMEServerとSingnalingServerのdocker-composeはまとめないんですか？

2024-02-27 01:19 UTC, sus-yoshikane-t commented on Runtime/OmeWebSocket.cs
> +            var currentRetryCount = subscribeRetryCounts.ContainsKey(message.ClientId) ? subscribeRetryCounts[message.ClientId] : 0;
修正しました。https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/520b15804649bd85c24c3f6e1b63f12c118407f8

2024-02-27 01:20 UTC, sus-yoshikane-t commented on Runtime/OmeConfig.cs
> +        /// <param name="url">URL of the signaling server</param>
修正しました。https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/39dad16207d4d91f27d34f41793f81c5af440839

2024-02-27 02:36 UTC, mahaweilu commented on SignalingServer~/src/index.ts
> +const log = (message: string) => isLogging && console.log(message);
対応しました。
[69a9735](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/69a9735b8a6f0b5866b7134eb2c65fa21121178c)

2024-02-27 03:04 UTC, mahaweilu commented on SignalingServer~/src/index.ts
> +  Deno.serve({
対応しました。
[b630edc](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/b630edc37e134a283858a8976419dfc820065134)

2024-02-27 03:06 UTC, mahaweilu commented on SignalingServer~/src/index.ts
> +  let clientId = "";
対応しました。
[be3d873](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/be3d8738c49ab31c2e54c9d290c8997ee1f338ab)

2024-02-27 10:26 UTC, mahaweilu commented on OMEServer~/README.md
> +  - OBS Studio
以下で対応しました。
[6bdb8f7](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/6bdb8f757e5db90eb5fc05dad8ba4fcb3f909bb8)

2024-02-27 10:27 UTC, mahaweilu commented on OMEServer~/ansible/README.md
> +## Ansible のインストール
必要なもの/設定だけを残すように修正しました。
[6bdb8f7](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/6bdb8f757e5db90eb5fc05dad8ba4fcb3f909bb8)

[03114c8](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/03114c8d78abf652a483b8cdbaae262565515fda)

[16c1f22](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/16c1f2234c07b14757683e4bd7df70326c164c7e)

2024-02-27 10:28 UTC, mahaweilu commented on OMEServer~/efs/sample.env
必要なもの/設定だけを残すように修正しました。
[6bdb8f7](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/6bdb8f757e5db90eb5fc05dad8ba4fcb3f909bb8)、
[03114c8](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/03114c8d78abf652a483b8cdbaae262565515fda)、
[16c1f22](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/16c1f2234c07b14757683e4bd7df70326c164c7e)

2024-02-27 10:28 UTC, mahaweilu commented on OMEServer~/docs/obs-live-settings.png
必要なもの/設定だけを残すように修正しました。
[6bdb8f7](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/6bdb8f757e5db90eb5fc05dad8ba4fcb3f909bb8)、
[03114c8](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/03114c8d78abf652a483b8cdbaae262565515fda)、
[16c1f22](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/16c1f2234c07b14757683e4bd7df70326c164c7e)

2024-02-27 10:30 UTC, mahaweilu commented on OMEServer~/efs/sample.env
> +# 社内でWebSocketを繋ぐためには443ポートを使う（デフォルト: 3334）
必要なもの/設定だけを残すように修正しました。
[6bdb8f7](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/6bdb8f757e5db90eb5fc05dad8ba4fcb3f909bb8)、
[03114c8](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/03114c8d78abf652a483b8cdbaae262565515fda)、
[16c1f22](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/16c1f2234c07b14757683e4bd7df70326c164c7e)

2024-02-27 10:30 UTC, mahaweilu commented on OMEServer~/keys
必要なもの/設定だけを残すように修正しました。
[6bdb8f7](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/6bdb8f757e5db90eb5fc05dad8ba4fcb3f909bb8)、
[03114c8](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/03114c8d78abf652a483b8cdbaae262565515fda)、
[16c1f22](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/16c1f2234c07b14757683e4bd7df70326c164c7e)

2024-02-27 10:31 UTC, mahaweilu commented on OMEServer~/.env
> +# TLS/SSL証明書
以下修正で不要なコメントを削除して対応しました。
>必要なもの/設定だけを残すように修正しました。
[6bdb8f7](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/6bdb8f757e5db90eb5fc05dad8ba4fcb3f909bb8)、
[03114c8](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/03114c8d78abf652a483b8cdbaae262565515fda)、
[16c1f22](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/16c1f2234c07b14757683e4bd7df70326c164c7e)

2024-02-27 10:32 UTC, mahaweilu commented on OMEServer~/OMEServer.code-workspace
> +{
以下修正で対応しました。
>必要なもの/設定だけを残すように修正しました。
[6bdb8f7](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/6bdb8f757e5db90eb5fc05dad8ba4fcb3f909bb8)、
[03114c8](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/03114c8d78abf652a483b8cdbaae262565515fda)、
[16c1f22](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/16c1f2234c07b14757683e4bd7df70326c164c7e)

2024-02-28 00:17 UTC, mahaweilu commented on WebScripts~/src/OmeWebSocket.ts
> +                // const sdpMid = candidate.sdpMid;
削除して対応しました。
[05824b2](https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1/commits/05824b2179ba3832b6703a75c3899bb36f25a90a)

2024-02-28 00:20 UTC, mahaweilu commented on SignalingServer~/docker-compose.yml
> +version: '3.8'
現状にAWS EC2も別々となっています。一旦まとめないこととなったので対応不要です。

2024-02-28 00:31 UTC, mahaweilu commented on package.json
> +    "com.endel.nativewebsocket": "1.1.4",
Extreal.DevでPackage Managerに"com.endel"を追加して対応しました。以下PRに変更が入っています。
 https://github.com/extreal-dev/Extreal.Dev/pull/6/files

2024-02-28 00:45 UTC, mahaweilu commented on Runtime/Extreal.Integration.SFU.OME.asmdef
レビュー後で対応することになっています。（Multiplay部分のライブラリでそうしていました）

2024-02-28 00:51 UTC, mahaweilu commented on Samples~/MVS/ClientControl/ClientControlScope.cs
> +                        "stun:stun.l.google.com:19302",
P2P.WebRTCに合わせています。
https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/blob/main/Samples~/MVS/ClientControl/ClientControlScope.cs

2024-02-28 01:54 UTC, mahaweilu commented on OMEServer~/docker-compose.yml
> +      #- ${SSL_SERVER_CERT}:${OME_TLS_CERT_PATH}:ro
>AWS上で動作する際には
Extrealでクラウド（AWS）上にデプロイする場合の設定などは利用者に譲ることになっています。AWSサーバ側の証明書やcomposeファイル設定などの変更が入ったファイルを一旦S3に格納するようにします。

2024-02-28 03:52 UTC, kiyohome approved these changes

2024-02-28 08:00 UTC, sasuke9410 commented on OMEServer~/README.md
> +  - OBS Studio
確認しました！

2024-02-28 08:02 UTC, sasuke9410 commented on OMEServer~/ansible/README.md
> +## Ansible のインストール
Ansibleがディレクトリごと削除されていることを確認しました

2024-02-28 08:17 UTC, sasuke9410 commented on OMEServer~/efs/sample.env
・efsがディレクトリごと消されていること
・.envが直下に、Server.xmlがconf下に配置されていることを確認しました。

2024-02-28 08:32 UTC, sasuke9410 commented on package.json
> +    "com.endel.nativewebsocket": "1.1.4",
確認しました！

2024-02-28 08:39 UTC, sasuke9410 commented on OMEServer~/docker-compose.yml
> +      #- ${SSL_SERVER_CERT}:${OME_TLS_CERT_PATH}:ro
AWS用の設定項目が削除されていることを確認しました

2024-02-28 08:40 UTC, sasuke9410 commented on OMEServer~/efs/sample.env
> +# 社内でWebSocketを繋ぐためには443ポートを使う（デフォルト: 3334）
該当箇所が削除されていることを確認しました。

2024-02-28 08:45 UTC, sasuke9410 commented on OMEServer~/keys
削除されていることを確認しました

2024-02-28 08:46 UTC, sasuke9410 commented on Samples~/MVS/ClientControl/ClientControlScope.cs
> +                        "stun:stun.l.google.com:19302",
理解しました、問題なしです

2024-02-28 08:46 UTC, sasuke9410 commented on Runtime/Extreal.Integration.SFU.OME.asmdef
了解です

2024-02-28 08:48 UTC, sasuke9410 commented on Runtime/OmeWebSocket.cs
> +            var currentRetryCount = subscribeRetryCounts.ContainsKey(message.ClientId) ? subscribeRetryCounts[message.ClientId] : 0;
確認しました

2024-02-28 08:48 UTC, sasuke9410 commented on Runtime/OmeConfig.cs
> +        /// <param name="url">URL of the signaling server</param>
確認しました

2024-02-28 08:48 UTC, sasuke9410 approved these changes

2024-02-28 08:49 UTC, sasuke9410 approved these changes

2024-02-28 08:53 UTC, sasuke9410 approved these changes

2024-02-29 08:18 UTC, kiyohome approved these changes

2024-02-29 08:18 UTC, merged